const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
function load(file,imports={}){const module={exports:{}};const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(js,{module,exports:module.exports,require:n=>imports[n],URL,Date,Intl,Set,console});return module.exports;}
const categories=load('lib/gift-categories.ts');const selection=load('lib/gift-selection.ts',{'@/lib/gift-categories':categories});const feed=load('lib/gift-sheet-feed.ts');
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
const products=Array.from({length:20},(_,i)=>({id:'id'+String(i).padStart(2,'0'),price:500+i*100,categories:i%2?['colleague']:['cosy'],interests:i%3?['coffee']:['games'],tags:[]}));
check('daily order changes without losing relevant gifts',()=>{const a=selection.selectGifts(products,{category:'colleague',budget:1500,interest:'coffee'},'2026-10-10'),b=selection.selectGifts(products,{category:'colleague',budget:1500,interest:'coffee'},'2026-10-11');assert.ok(a.length>1);assert.notEqual(a[0].id,b[0].id);assert.deepEqual([...a.map(p=>p.id)].sort(),[...b.map(p=>p.id)].sort());assert.ok(a.every(p=>p.price<=1500&&p.categories.includes('colleague')&&p.interests.includes('coffee')));});
check('same day stable despite catalogue input order',()=>assert.equal(JSON.stringify(selection.selectGifts(products,{},'2026-10-10')),JSON.stringify(selection.selectGifts([...products].reverse(),{},'2026-10-10'))));
check('UK day uses daylight saving',()=>assert.equal(selection.londonDay(new Date('2026-10-10T23:30:00Z')),'2026-10-11'));
check('invalid filters discarded',()=>assert.equal(selection.readGiftFilters({budget:'-1',interest:'private',category:'invalid'}).budget,undefined));
const headers=['id','title','price','shop','tags','url','image','description','deliveryNote','categories','interests','priceCheckedAt'];
const quote=v=>'"'+String(v).replaceAll('"','""')+'"';const csv=r=>headers.join(',')+'\n'+r.map(quote).join(',');const row=['CMB-GIFT-0001','A mug',1999,'Shop','coffee','https://www.johnlewis.com/widget/p123','','Description, with "quotes"\nand newline','Delivery extra','colleague','coffee',new Date().toISOString()];
check('quoted CSV and current GBP pence parsed',()=>{const p=feed.parseGiftFeed(csv(row))[0];assert.equal(p.price,1999);assert.equal(p.description,row[7]);});
check('stale prices and arbitrary links excluded',()=>{const stale=[...row];stale[11]='2020-01-01';assert.equal(feed.parseGiftFeed(csv(stale)).length,0);const unsafe=[...row];unsafe[5]='https://evil.example/';assert.equal(feed.parseGiftFeed(csv(unsafe)).length,0);});
check('unknown image host excluded',()=>{const r=[...row];r[6]='https://evil.example/image';assert.equal(feed.parseGiftFeed(csv(r))[0].image,'');});
check('duplicate IDs and bad schema excluded',()=>{assert.equal(feed.parseGiftFeed(csv(row)+'\n'+row.map(quote).join(',')).length,1);assert.throws(()=>feed.parseGiftFeed('id,private\nsecret,note'));});
console.log(checks+' gift selection and feed checks passed');

check('approved master exports through CSV to relevant daily picks',()=>{const ctx=vm.createContext({console});vm.runInContext(fs.readFileSync('scripts/gift-verifier/Code.gs','utf8'),ctx);const productUrl='https://www.johnlewis.com/widget/p123';const m={gift_id:'CMB-GIFT-0500',publication_status:'published',approval_status:'approved',approved_by:'Owner',approved_date:'2026-10-10',product_url:productUrl,product_name:'Widget',short_description:'A useful widget',retailer:'Shop',categories:'colleague',recipient_interests:'technology'};const o=['CMB-GIFT-0500',productUrl,new Date().toISOString(),'verified',200,'Widget',9.99,'no','in-stock'];const exported=ctx.websiteRows_([m],[o],Date.now());const parsed=feed.parseGiftFeed(headers.join(',')+'\n'+exported[0].map(quote).join(','));const selected=selection.selectGifts(parsed,{category:'colleague',budget:1000,interest:'technology'});assert.equal(selected.length,1);assert.equal(selected[0].id,m.gift_id);assert.equal(selected[0].price,999);});
console.log(checks+' total gift flow checks passed');
